[build]
  command = "set NODE_ENV=production && npm run build"
  publish = "dist"
  base = "."
  functions = "server"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"

# Configuração para funções serverless
[functions]
  directory = "server"

# Redireciona todas as requisições para o index.html para suportar SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200