[build]
  command = "set NODE_ENV=production && npm run build"
  publish = "dist"
  functions = "server"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["drizzle-orm", "drizzle-orm/postgres-js/migrator"]